package com.zy.dao.model;

import java.util.Date;

public class ZYCase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.case_id
	 * @mbggenerated
	 */
	private Integer caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.style_id
	 * @mbggenerated
	 */
	private Integer styleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.designer_id
	 * @mbggenerated
	 */
	private Integer designerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.update_time
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.insert_time
	 * @mbggenerated
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zyzs_case.name
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.case_id
	 * @return  the value of zyzs_case.case_id
	 * @mbggenerated
	 */
	public Integer getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.case_id
	 * @param caseId  the value for zyzs_case.case_id
	 * @mbggenerated
	 */
	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.style_id
	 * @return  the value of zyzs_case.style_id
	 * @mbggenerated
	 */
	public Integer getStyleId() {
		return styleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.style_id
	 * @param styleId  the value for zyzs_case.style_id
	 * @mbggenerated
	 */
	public void setStyleId(Integer styleId) {
		this.styleId = styleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.des
	 * @return  the value of zyzs_case.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.des
	 * @param des  the value for zyzs_case.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des == null ? null : des.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.address
	 * @return  the value of zyzs_case.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.address
	 * @param address  the value for zyzs_case.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.designer_id
	 * @return  the value of zyzs_case.designer_id
	 * @mbggenerated
	 */
	public Integer getDesignerId() {
		return designerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.designer_id
	 * @param designerId  the value for zyzs_case.designer_id
	 * @mbggenerated
	 */
	public void setDesignerId(Integer designerId) {
		this.designerId = designerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.update_time
	 * @return  the value of zyzs_case.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.update_time
	 * @param updateTime  the value for zyzs_case.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.insert_time
	 * @return  the value of zyzs_case.insert_time
	 * @mbggenerated
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.insert_time
	 * @param insertTime  the value for zyzs_case.insert_time
	 * @mbggenerated
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zyzs_case.name
	 * @return  the value of zyzs_case.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zyzs_case.name
	 * @param name  the value for zyzs_case.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}