package com.zy.dao.model;

import java.util.Date;

public class ZYDesigner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.designer_id
     *
     * @mbggenerated
     */
    private Integer designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.worktime
     *
     * @mbggenerated
     */
    private String worktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.photo_path
     *
     * @mbggenerated
     */
    private String photoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.concept
     *
     * @mbggenerated
     */
    private String concept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.works
     *
     * @mbggenerated
     */
    private String works;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.honor
     *
     * @mbggenerated
     */
    private String honor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zyzs_designer.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.designer_id
     *
     * @return the value of zyzs_designer.designer_id
     *
     * @mbggenerated
     */
    public Integer getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.designer_id
     *
     * @param designerId the value for zyzs_designer.designer_id
     *
     * @mbggenerated
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.name
     *
     * @return the value of zyzs_designer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.name
     *
     * @param name the value for zyzs_designer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.worktime
     *
     * @return the value of zyzs_designer.worktime
     *
     * @mbggenerated
     */
    public String getWorktime() {
        return worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.worktime
     *
     * @param worktime the value for zyzs_designer.worktime
     *
     * @mbggenerated
     */
    public void setWorktime(String worktime) {
        this.worktime = worktime == null ? null : worktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.photo_path
     *
     * @return the value of zyzs_designer.photo_path
     *
     * @mbggenerated
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.photo_path
     *
     * @param photoPath the value for zyzs_designer.photo_path
     *
     * @mbggenerated
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.concept
     *
     * @return the value of zyzs_designer.concept
     *
     * @mbggenerated
     */
    public String getConcept() {
        return concept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.concept
     *
     * @param concept the value for zyzs_designer.concept
     *
     * @mbggenerated
     */
    public void setConcept(String concept) {
        this.concept = concept == null ? null : concept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.works
     *
     * @return the value of zyzs_designer.works
     *
     * @mbggenerated
     */
    public String getWorks() {
        return works;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.works
     *
     * @param works the value for zyzs_designer.works
     *
     * @mbggenerated
     */
    public void setWorks(String works) {
        this.works = works == null ? null : works.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.honor
     *
     * @return the value of zyzs_designer.honor
     *
     * @mbggenerated
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.honor
     *
     * @param honor the value for zyzs_designer.honor
     *
     * @mbggenerated
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.update_time
     *
     * @return the value of zyzs_designer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.update_time
     *
     * @param updateTime the value for zyzs_designer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zyzs_designer.insert_time
     *
     * @return the value of zyzs_designer.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zyzs_designer.insert_time
     *
     * @param insertTime the value for zyzs_designer.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}