package com.zy.dao.mapper;

import com.zy.dao.model.ZYCase;
import com.zy.dao.model.ZYCaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZYCaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int countByExample(ZYCaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int deleteByExample(ZYCaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer caseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int insert(ZYCase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int insertSelective(ZYCase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	List<ZYCase> selectByExample(ZYCaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	ZYCase selectByPrimaryKey(Integer caseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ZYCase record,
			@Param("example") ZYCaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ZYCase record,
			@Param("example") ZYCaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ZYCase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_case
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ZYCase record);
}