package com.zy.dao.mapper;

import com.zy.dao.model.ZYCraft;
import com.zy.dao.model.ZYCraftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZYCraftMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int countByExample(ZYCraftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int deleteByExample(ZYCraftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer craftId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int insert(ZYCraft record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int insertSelective(ZYCraft record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	List<ZYCraft> selectByExample(ZYCraftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	ZYCraft selectByPrimaryKey(Integer craftId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ZYCraft record,
			@Param("example") ZYCraftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ZYCraft record,
			@Param("example") ZYCraftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ZYCraft record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_craft
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ZYCraft record);
}