package com.zy.dao.mapper;

import com.zy.dao.model.ZYDesigner;
import com.zy.dao.model.ZYDesignerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZYDesignerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int countByExample(ZYDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int deleteByExample(ZYDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer designerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int insert(ZYDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int insertSelective(ZYDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    List<ZYDesigner> selectByExample(ZYDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    ZYDesigner selectByPrimaryKey(Integer designerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZYDesigner record, @Param("example") ZYDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZYDesigner record, @Param("example") ZYDesignerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZYDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_designer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZYDesigner record);
}