package com.zy.dao.mapper;

import com.zy.dao.model.ZYImg;
import com.zy.dao.model.ZYImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZYImgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int countByExample(ZYImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int deleteByExample(ZYImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer imgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int insert(ZYImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int insertSelective(ZYImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	List<ZYImg> selectByExample(ZYImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	ZYImg selectByPrimaryKey(Integer imgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ZYImg record,
			@Param("example") ZYImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ZYImg record,
			@Param("example") ZYImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ZYImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zyzs_img
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ZYImg record);
}