package com.zy.dao.mapper;

import com.zy.dao.model.ZYStyle;
import com.zy.dao.model.ZYStyleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZYStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int countByExample(ZYStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int deleteByExample(ZYStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int insert(ZYStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int insertSelective(ZYStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    List<ZYStyle> selectByExample(ZYStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    ZYStyle selectByPrimaryKey(Integer styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZYStyle record, @Param("example") ZYStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZYStyle record, @Param("example") ZYStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZYStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zyzs_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZYStyle record);
}